### ISSUE TITLE
Set up CI workflow to build and push Docker images to DockerHub

### ISSUE THREAD

**Issue by brianbruff** [brianbruff/pileup-buster#18]
## Overview
This issue is to implement a GitHub Actions workflow that will automatically build and push Docker images to DockerHub when changes are pushed to the master branch.

## Requirements
- Use the existing 'prod' environment which contains:
  - Secret `GITHUB_PAT` (GitHub personal access token)
  - Environment variable `GITHUB_NAME` (DockerHub username)
- The workflow should:
  1. Trigger when code is pushed to the master branch
  2. Use GitHub's docker metadata action to extract semantic version from the repository
  3. Build the Docker image
  4. Push the image to DockerHub with the semantic version tag

## Proposed Implementation
Create a new GitHub Actions workflow file `.github/workflows/docker-build-push.yml` with the following structure:

```yaml
name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.GITHUB_NAME }}
          password: ${{ secrets.GITHUB_PAT }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GITHUB_NAME }}/pileup-buster
          tags: |
            type=semver,pattern={{version}}
            type=sha
            
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

## Acceptance Criteria
- [ ] Workflow file is created and committed to the repository
- [ ] Workflow runs successfully when changes are pushed to master
- [ ] Docker image is built and pushed to DockerHub with the correct semantic version tag
- [ ] The workflow uses the proper environment variables and secrets from the 'prod' environment
